name: Manual Trigger Test Workflow
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_JEL_KEY }}
            ARGS: "--delete"
            SOURCE: "."
            REMOTE_HOST: "gate.paas.massivegrid.com"
            REMOTE_USER: "127221-38"
            REMOTE_PORT: 3022
            TARGET: "/var/www/webroot/ROOT"
            EXCLUDE: "/dist/, /node_modules/"
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "TEEEESSSSTTT!!!"
      - name: Debug_stuff
        run: echo "{ runner.os }"
      - name: Debug_stuff_2
        run: echo "{{ runner.os }}"
      - name: Debug_stuff_3
        run: echo "${{runner.os}}"
        

